"""added ondelete for TaskUser

Revision ID: 6904cb86f998
Revises: 62135c6481fd
Create Date: 2023-09-14 00:54:32.302707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6904cb86f998'
down_revision: Union[str, None] = '62135c6481fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_users_task_id_fkey', 'tasks_users', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_users', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_users', type_='foreignkey')
    op.create_foreign_key('tasks_users_task_id_fkey', 'tasks_users', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
