"""added completed bool to Task model

Revision ID: 992fe60eeb1f
Revises: 29841c6c511a
Create Date: 2023-09-15 03:45:12.882066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992fe60eeb1f'
down_revision: Union[str, None] = '29841c6c511a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('completed', sa.Boolean(), nullable=True, default=False),)
    tasks = sa.table('tasks', sa.column('completed'))  
    op.execute(tasks.update().values(completed=False))
    op.alter_column('tasks', 'completed', nullable=False)       
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'completed')
    # ### end Alembic commands ###
