"""added ondelete for TaskUser user_id

Revision ID: 7cd158c555f3
Revises: 6904cb86f998
Create Date: 2023-09-14 01:04:18.918552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd158c555f3'
down_revision: Union[str, None] = '6904cb86f998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_users_user_id_fkey', 'tasks_users', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks_users', type_='foreignkey')
    op.create_foreign_key('tasks_users_user_id_fkey', 'tasks_users', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
