"""RefreshSessions ondelete added

Revision ID: a57a04e71996
Revises: 8e50930acff8
Create Date: 2023-09-12 02:42:54.810666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a57a04e71996'
down_revision: Union[str, None] = '8e50930acff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_sessions_user_id_fkey', 'refresh_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_sessions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_sessions', type_='foreignkey')
    op.create_foreign_key('refresh_sessions_user_id_fkey', 'refresh_sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
